export const featuredImages = [
  {
    src: '/images/featuredi.png',
    alt: 'Featured image 1',
    width: 381,
    height: 263
  },
  {
    src: '/images/featuredii.png',
    alt: 'Featured image 2',
    width: 381,
    height: 263
  },
  {
    src: '/images/featurediii.png',
    alt: 'Featured image 3',
    width: 381,
    height: 263
  },
  {
    src: '/images/featurediv.png',
    alt: 'Featured image 4',
    width: 381,
    height: 263
  },
]

export const savedList = [
  {
    image: '/images/viewedi.png',
    date: '27 April, 2023',
    title: 'Digital marketing made simple',
    podcaster: 'Julie Morgan',
    length: '30 Min',
    link: '/saved-list'
  },
  {
    image: '/images/featuredi.png',
    date: '27 April, 2023',
    title: 'Design details',
    podcaster: 'George Brian',
    length: '15 Min',
    link: '/saved-list'
  },
  {
    image: '/images/viewediv.png',
    date: '8 June, 2023',
    title: 'Art of Cryptocurrency',
    podcaster: 'Enoch Timothy',
    length: '1 hour',
    link: '/saved-list'
  },
]

export const guestList = [
  {
    image: '/images/viewedi.png',
    title: 'Digital marketing made simple',
    podcaster: 'Julie Morgan',
  },
  {
    image: '/images/viewediii.png',
    title: 'Design details',
    podcaster: 'George Brian',
  },
  {
    image: '/images/viewedviii.png',
    title: 'Art of Cryptocurrency',
    podcaster: 'Enoch Timothy',
  },
  {
    image: '/images/viewedii.png',
    title: 'Communication',
    podcaster: 'Anne Rice',
  },
  {
    image: '/images/viewedv.png',
    title: 'Interviews and more',
    podcaster: 'The Crew',
  },
  {
    image: '/images/viewedix.png',
    title: 'Relationship matters',
    podcaster: 'Jane Brayan',
  },
  {
    image: '/images/viewedVii.png',
    title: 'Entertainment: Music and Movies',
    podcaster: 'Frank B. Stones',
  },
  {
    image: '/images/viewedvi.png',
    title: 'Interviews and more',
    podcaster: 'John and June',
  },
  {
    image: '/images/viewediv.png',
    title: 'Discoveries',
    podcaster: 'Personalised Discovery',
  },
]

export const podcastList = [
  {
    image: '/images/viewedi.png',
    title: 'Digital marketing made simple',
    podcaster: 'Julie Morgan',
  },
  {
    image: '/images/viewediii.png',
    title: 'Design details',
    podcaster: 'George Brian',
  },
  {
    image: '/images/viewedviii.png',
    title: 'Art of Cryptocurrency',
    podcaster: 'Enoch Timothy',
  },
  {
    image: '/images/viewedii.png',
    title: 'Communication',
    podcaster: 'Anne Rice',
  },
  {
    image: '/images/viewedv.png',
    title: 'Interviews and more',
    podcaster: 'The Crew',
  },
  {
    image: '/images/viewedix.png',
    title: 'Relationship matters',
    podcaster: 'Jane Brayan',
  },
  {
    image: '/images/viewedVii.png',
    title: 'Entertainment: Music and Movies',
    podcaster: 'Frank B. Stones',
  },
  {
    image: '/images/viewedvi.png',
    title: 'Interviews and more',
    podcaster: 'John and June',
  },
  {
    image: '/images/viewediv.png',
    title: 'Discoveries',
    podcaster: 'Personalised Discovery',
  },
]

export const dropdown_options = [{ option: 'Location 1' }, { option: 'Location 2' }, { option: 'Location 3' }, { option: 'Location 4' }]

export const gender_options = [{ option: '' }, { option: 'Male' }, { option: 'Female' }, { option: 'Non-Binary' }, { option: 'Prefer not to say' }]

export const new_options = [{ option: '' }, { option: 'New' }, { option: 'Featured' }]

export const category_options = [
  { option: '' },
  { option: 'Arts' },
  { option: 'Business' },
  { option: 'Comedy' },
  { option: 'Education' },
  { option: 'Fiction' },
  { option: 'Finance' },
  { option: 'Government' },
  { option: 'History' },
  { option: 'Health & Fitness' },
  { option: 'Kids & Family' },
  { option: 'Leisure' },
  { option: 'Music' },
  { option: 'News' },
  { option: 'Religion & Spirituality' },
  { option: 'Science' },
  { option: 'Society & Culture' },
  { option: 'Sports' },
  { option: 'Technology' },
  { option: 'True Crime' },
  { option: 'TV & Film' }
]



export const age_options = [
  { option: '' },
  { option: '18-25 years old' },
  { option: '26-30 years old' },
  { option: '30-45 years old' },
  { option: '45 and above years old' }
]



export const country_options = [
  { option: '' },
  { option: 'Afghanistan' },
  { option: 'Albania' },
  { option: 'Algeria' },
  { option: 'Andorra' },
  { option: 'Angola' },
  { option: 'Antigua and Barbuda' },
  { option: 'Argentina' },
  { option: 'Armenia' },
  { option: 'Australia' },
  { option: 'Austria' },
  { option: 'Azerbaijan' },
  { option: 'The Bahamas' },
  { option: 'Bahrain' },
  { option: 'Bangladesh' },
  { option: 'Barbados' },
  { option: 'Belarus' },
  { option: 'Belgium' },
  { option: 'Belize' },
  { option: 'Benin' },
  { option: 'Bhutan' },
  { option: 'Bolivia' },
  { option: 'Bosnia and Herzegovina' },
  { option: 'Botswana' },
  { option: 'Brazil' },
  { option: 'Brunei' },
  { option: 'Bulgaria' },
  { option: 'Burkina Faso' },
  { option: 'Burundi' },
  { option: 'Cabo Verde' },
  { option: 'Cambodia' },
  { option: 'Cameroon' },
  { option: 'Canada' },
  { option: 'Central African Republic' },
  { option: 'Chad' },
  { option: 'Chile' },
  { option: 'China' },
  { option: 'Colombia' },
  { option: 'Comoros' },
  { option: 'Democratic Republic of the Congo' },
  { option: 'Republic of the Congo' },
  { option: 'Costa Rica' },
  { option: 'Côte d’Ivoire' },
  { option: 'Croatia' },
  { option: 'Cuba' },
  { option: 'Cyprus' },
  { option: 'Czech Republic' },
  { option: 'Denmark' },
  { option: 'Djibouti' },
  { option: 'Dominica' },
  { option: 'Dominican Republic' },
  { option: 'East Timor(Timor Leste)' },
  { option: 'Ecuador' },
  { option: 'Egypt' },
  { option: 'El Salvador' },
  { option: 'Equatorial Guinea' },
  { option: 'Eritrea' },
  { option: 'Estonia' },
  { option: 'Eswatini' },
  { option: 'Ethiopia' },
  { option: 'Fiji' },
  { option: 'Finland' },
  { option: 'France' },
  { option: 'Gabon' },
  { option: 'The Gambia' },
  { option: 'Georgia' },
  { option: 'Germany' },
  { option: 'Ghana' },
  { option: 'Greece' },
  { option: 'Grenada' },
  { option: 'Guatemala' },
  { option: 'Guinea' },
  { option: 'Guinea Bissau' },
  { option: 'Guyana' },
  { option: 'Haiti' },
  { option: 'Honduras' },
  { option: 'Hungary' },
  { option: 'Iceland' },
  { option: 'India' },
  { option: 'Indonesia' },
  { option: 'Iran' },
  { option: 'Iraq' },
  { option: 'Ireland' },
  { option: 'Israel' },
  { option: 'Italy' },
  { option: 'Jamaica' },
  { option: 'Japan' },
  { option: 'Jordan' },
  { option: 'Kazakhstan' },
  { option: 'Kenya' },
  { option: 'Kiribati' },
  { option: 'Kosovo' },
  { option: 'Kuwait' },
  { option: 'Kyrgyzstan' },
  { option: 'Laos' },
  { option: 'Latvia' },
  { option: 'Lebanon' },
  { option: 'Lesotho' },
  { option: 'Liberia' },
  { option: 'Libya' },
  { option: 'Liechtenstein' },
  { option: 'Lithuania' },
  { option: 'Luxembourg' },
  { option: 'Madagascar' },
  { option: 'Malawi' },
  { option: 'Malaysia' },
  { option: 'Maldives' },
  { option: 'Mali' },
  { option: 'Malta' },
  { option: 'Marshall Islands' },
  { option: 'Mauritania' },
  { option: 'Mauritius' },
  { option: 'Mexico' },
  { option: 'Federated States of Micronesia' },
  { option: 'Moldova' },
  { option: 'Monaco' },
  { option: 'Mongolia' },
  { option: 'Montenegro' },
  { option: 'Morocco' },
  { option: 'Mozambique' },
  { option: 'Myanmar(Burma)' },
  { option: 'Namibia' },
  { option: 'Nauru' },
  { option: 'Nepal' },
  { option: 'Netherlands' },
  { option: 'New Zealand' },
  { option: 'Nicaragua' },
  { option: 'Niger' },
  { option: 'Nigeria' },
  { option: 'North Korea' },
  { option: 'North Macedonia' },
  { option: 'Norway' },
  { option: 'Oman' },
  { option: 'Pakistan' },
  { option: 'Palau' },
  { option: 'Panama' },
  { option: 'Papua New Guinea' },
  { option: 'Paraguay' },
  { option: 'Peru' },
  { option: 'Philippines' },
  { option: 'Poland' },
  { option: 'Portugal' },
  { option: 'Qatar' },
  { option: 'Romania' },
  { option: 'Russia' },
  { option: 'Rwanda' },
  { option: 'Saint Kitts and Nevis' },
  { option: 'Saint Lucia' },
  { option: 'Saint Vincent and the Grenadines' },
  { option: 'Samoa' },
  { option: 'San Marino' },
  { option: 'Sao Tome and Principe' },
  { option: 'Saudi Arabia' },
  { option: 'Senegal' },
  { option: 'Serbia' },
  { option: 'Seychelles' },
  { option: 'Sierra Leone' },
  { option: 'Singapore' },
  { option: 'Slovakia' },
  { option: 'Slovenia' },
  { option: 'Solomon Islands' },
  { option: 'Somalia' },
  { option: 'South Africa' },
  { option: 'South Korea' },
  { option: 'Spain' },
  { option: 'Sri Lanka' },
  { option: 'Sudan' },
  { option: 'Sudan, South' },
  { option: 'Suriname' },
  { option: 'Sweden' },
  { option: 'Switzerland' },
  { option: 'Syria' },
  { option: 'Taiwan' },
  { option: 'Tajikistan' },
  { option: 'Tanzania' },
  { option: 'Thailand' },
  { option: 'Togo' },
  { option: 'Tonga' },
  { option: 'Trinidad and Tobago' },
  { option: 'Tunisia' },
  { option: 'Turkey' },
  { option: 'Turkmenistan' },
  { option: 'Tuvalu' },
  { option: 'Uganda' },
  { option: 'Ukraine' },
  { option: 'United Arab Emirates' },
  { option: 'United Kingdom' },
  { option: 'United States' },
  { option: 'Uruguay' },
  { option: 'Uzbekistan' },
  { option: 'Vanuatu' },
  { option: 'Vatican City' },
  { option: 'Venezuela' },
  { option: 'Vietnam' },
  { option: 'Yemen' },
  { option: 'Zambia' },
  { option: 'Zimbabwe' }
]



export const language_options = [
  { option: '' },
  { option: 'English' },
  { option: 'Afrikaans' },
  { option: 'Albanian' },
  { option: 'Amharic' },
  { option: 'Arabic' },
  { option: 'Armenian' },
  { option: 'Assamese' },
  { option: 'Aymara' },
  { option: 'Azerbaijani' },
  { option: 'Bambara' },
  { option: 'Basque' },
  { option: 'Belarusian' },
  { option: 'Bengali' },
  { option: 'Bhojpuri' },
  { option: 'Bosnian' },
  { option: 'Bulgarian' },
  { option: 'Catalan' },
  { option: 'Cebuano' },
  { option: 'Chinese' },
  { option: 'Corsican' },
  { option: 'Croatian' },
  { option: 'Czech' },
  { option: 'Danish' },
  { option: 'Dhivehi' },
  { option: 'Dogri' },
  { option: 'Dutch' },
  { option: 'Esperanto' },
  { option: 'Estonian' },
  { option: 'Ewe' },
  { option: 'Filipino' },
  { option: 'Finnish' },
  { option: 'French' },
  { option: 'Frisian' },
  { option: 'Galician' },
  { option: 'Georgian' },
  { option: 'German' },
  { option: 'Greek' },
  { option: 'Guarani' },
  { option: 'Gujarati' },
  { option: 'Haitian Creole' },
  { option: 'Hausa' },
  { option: 'Hawaiian' },
  { option: 'Hebrew' },
  { option: 'Hindi' },
  { option: 'Hmong' },
  { option: 'Hungarian' },
  { option: 'Icelandic' },
  { option: 'Igbo' },
  { option: 'Ilocano' },
  { option: 'Indonesian' },
  { option: 'Irish' },
  { option: 'Italian' },
  { option: 'Japanese' },
  { option: 'Javanese' },
  { option: 'Kannada' },
  { option: 'Kazakh' },
  { option: 'Khmer' },
  { option: 'Kinyarwanda' },
  { option: 'Konkani' },
  { option: 'Korean' },
  { option: 'Krio' },
  { option: 'Kurdish' },
  { option: 'Kyrgyz' },
  { option: 'Lao' },
  { option: 'Latin' },
  { option: 'Latvian' },
  { option: 'Lingala' },
  { option: 'Lithuanian' },
  { option: 'Luganda' },
  { option: 'Luxembourgish' },
  { option: 'Macedonian' },
  { option: 'Maithili' },
  { option: 'Malagasy' },
  { option: 'Malay' },
  { option: 'Malayalam' },
  { option: 'Maltese' },
  { option: 'Maori' },
  { option: 'Marathi' },
  { option: 'Meiteilon' },
  { option: 'Mizo' },
  { option: 'Mongolian' },
  { option: 'Myanmar' },
  { option: 'Nepali' },
  { option: 'Norwegian' },
  { option: 'Nyanja' },
  { option: 'Odia' },
  { option: 'Oromo' },
  { option: 'Pashto' },
  { option: 'Persian' },
  { option: 'Polish' },
  { option: 'Portuguese' },
  { option: 'Punjabi' },
  { option: 'Romanian' },
  { option: 'Russian' },
  { option: 'Samoan' },
  { option: 'Sanskrit' },
  { option: 'Scots Gaelic' },
  { option: 'Sepedi' },
  { option: 'Serbian' },
  { option: 'Sesotho' },
  { option: 'Shona' },
  { option: 'Sindhi' },
  { option: 'Sinhala' },
  { option: 'Slovak' },
  { option: 'Slovenian' },
  { option: 'Somali' },
  { option: 'Spanish' },
  { option: 'Sundanese' },
  { option: 'Swahili' },
  { option: 'Swedish' },
  { option: 'Tagalog' },
  { option: 'Tamil' },
  { option: 'Tatar' },
  { option: 'Telugu' },
  { option: 'Thai' },
  { option: 'Tigrinya' },
  { option: 'Tsonga' },
  { option: 'Turkish' },
  { option: 'Turkmen' },
  { option: 'Twi' },
  { option: 'Ukrainian' },
  { option: 'Urdu' },
  { option: 'Uyghur' },
  { option: 'Uzbek' },
  { option: 'Vietnamese' },
  { option: 'Welsh' },
  { option: 'Xhosa' },
  { option: 'Yiddish' },
  { option: 'Yoruba' },
  { option: 'Zulu' }
]
